Added information about menthor
htmlacademy-javascript/2319345-kekstagram-29 pull request #1
Opened 2023-06-08 20:09 UTC by iskalinina

2023-06-08 20:18 UTC, baileys-li requested changes

2023-06-08 20:18 UTC, baileys-li commented on Readme.md
> +* Наставник: `Arthur Litovko`.
Давай я тоже буду ссылкой
```suggestion
* Наставник: [Arthur Litovko](https://github.com/baileys-li).
```

2023-06-09 04:07 UTC, iskalinina commented on Readme.md
> +* Наставник: `Arthur Litovko`.
Сделано)

2023-06-09 04:16 UTC, baileys-li approved these changes

2023-06-09 04:16 UTC, merged